# Generated by Django 6.1.1 on 2026-09-17 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_paciente_ciudad_paciente_sexo_and_more'),
        ('usuarios', '0002_perfilusuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField()),
                ('antecedentes_medicos', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos_actuales', models.TextField(blank=True)),
                ('antecedentes_odontologicos', models.TextField(blank=True)),
                ('habitos', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('odontologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_clinicas', to='usuarios.perfilusuario')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='pacientes.paciente')),
            ],
        ),
    ]
